[theme]
# Primary color for interactive elements
primaryColor = "#FF6B6B"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar
secondaryBackgroundColor = "#F0F2F6"

# Text color
textColor = "#262730"

# Font family
font = "sans serif"

[server]
# Max upload size in MB (for CSV/Excel files)
maxUploadSize = 50

# Max message size in MB
maxMessageSize = 50

[browser]
# Tab title
gatherUsageStats = false

[client]
# Show error details
showErrorDetails = true

# Enable wide mode by default
showSidebarNavigation = true